### PR TITLE
Fix incompatibility with Electron renderer process

### LINKED ISSUE #21: Throws `setTimeout(...).unref is not a function` in Electron
Run the following code in an Electron renderer process (use https://www.electronjs.org/fiddle for faster repro):
```
const http = require('http');
const CacheableLookup = require('cacheable-lookup');
const cacheable = new CacheableLookup();
http.get('http://example.com', {lookup: cacheable.lookup});
```

It'll throw:
```
Uncaught TypeError: setTimeout(...).unref is not a function
    at CacheableLookup.tick (/private/var/folders/qp/tmp/T/tmp-/node_modules/cacheable-lookup/source/index.js:290)
    at CacheableLookup.query (/private/var/folders/qp/tmp/T/tmp-/node_modules/cacheable-lookup/source/index.js:176)
    at CacheableLookup.lookupAsync (/private/var/folders/qp/tmp/T/tmp-/node_modules/cacheable-lookup/source/index.js:137)
    at CacheableLookup.lookup (/private/var/folders/qp/tmp/T/tmp-/node_modules/cacheable-lookup/source/index.js:121)
    at net.js:1030
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:301)
    at lookupAndConnect (net.js:1029)
    at Socket.connect (net.js:963)
    at Agent.connect [as createConnection] (net.js:172)
    at Agent.createSocket (_http_agent.js:234)
```

Tried Electron 8.2.5 and 9.0.0-beta.22

Cross posted: https://github.com/sindresorhus/got/issues/1219

Addressed in https://github.com/electron/electron/issues/21162

Possible fix would be to conditionally call `unref()` if it exists. Or use `const { setTimeout } = require('timers')`

### PR DESCRIPTION
**Pull request by kaatt**
Fixes #21

Would be a good idea to add a test for this.

Not sure why tests are failing.

### CODE REVIEW

File: source/index.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ const {
 } = require('dns');
 const {promisify} = require('util');
 const os = require('os');
+const {setTimeout} = require('timers');
```
Comment (szmarczak) [inline source/index.js:12]: Is there an actual need to require `timers`? Isn't `if (timeout.unref) { timeout.unref(); }` enough?

I am not experienced with Electron nor I'm going to, so I really don't know.

Comment (kaatt) [reply source/index.js:12]: According to https://github.com/electron/electron/issues/21162, if we want `unref` to happen, that's necessary. I'm fine either way.

Comment (kaatt) [reply source/index.js:12]: It's a conditional in execa: https://github.com/sindresorhus/execa/blob/120230cade59099214905ac2a9136e406c0b6f3a/lib/kill.js#L24-L30

**Comment by szmarczak** [comment]
> Not sure why tests are failing.

https://github.com/szmarczak/cacheable-lookup/blob/6c5f5d5eed568240ac5b6febe913d5befd8bf5f3/tests/test.js#L762-L782

Since you're declaring `setTimeout`, it's no longer a global. So the solution is to use `proxyquire` in this test. I will the test this ASAP.

File: source/index.js (hunk 1 above)
Comment (szmarczak) [reply source/index.js:12]: > if we want unref to happen, that's necessary. I'm fine either way.

But does it have any effect?

Comment (kaatt) [reply source/index.js:12]: I'm guessing it does. Electron has node integration in the renderer process so instead of the blink setTimeout, the node setTimeout is used when you import timers.

Comment (kaatt) [reply source/index.js:12]: We can do both as well. It's not just Electron where .unref isn't a function. https://github.com/sindresorhus/get-port/pull/40/files

Comment (szmarczak) [reply source/index.js:12]: Okay, but `.unref()` makes the process exit if all other event loop tasks are finished. And since it's running in a renderer process, the process itself will run as long as the user keeps it open. So I don't think `.unref()` will have any effect here. If the end user decides to close the electron app, the timeouts are destroyed anyway.

Comment (szmarczak) [reply source/index.js:12]: You can remove this line if you decide to go with `if`.

File: source/index.js [hunk 2]
```diff
@@ -285,9 +286,14 @@ class CacheableLookup {
 
 		this._tickLocked = true;
 
-		setTimeout(() => {
+		const interval = setTimeout(() => {
```
Comment (szmarczak) [inline source/index.js:289]:
```suggestion
		const timeout = setTimeout(() => {
```

It's not an interval, it's a timeout :)

File: source/index.js [hunk 3]
```diff
@@ -285,9 +286,14 @@ class CacheableLookup {
...
 			this._tickLocked = false;
-		}, this._lockTime).unref();
+		}, this._lockTime);
+		
+		// unref is undefined in some environments
```
Comment (szmarczak) [inline source/index.js:293]:
```suggestion
		// There is no `timeout.unref()` when running inside an Electron renderer
```

File: source/index.js [hunk 4]
```diff
@@ -285,9 +286,14 @@ class CacheableLookup {
...
 		this._tickLocked = true;
 
-		setTimeout(() => {
+		const timeout = setTimeout(() => {
 			this._tickLocked = false;
-		}, this._lockTime).unref();
+		}, this._lockTime);
+		
+		// There is no `timeout.unref()` when running inside an Electron renderer
+		if (interval.unref) {
```
Comment (szmarczak) [inline source/index.js:294]: Unfortunately GitHub suggestions don't do variable renaming 😅

Comment (kaatt) [reply source/index.js]: just noticed :)

**Comment by kaatt** [comment]
ready for merge

**Comment by szmarczak** [comment]
Released 4.2.3
